### ISSUE TITLE
How to load the GraphML file to MetaGraphsNext.MGFormat instead

### ISSUE THREAD

**Issue by finn777-yea** [UniStuttgart-IKR/NestedGraphsIO.jl#8]
Hey, I wonder if there is an efficient way to load the GraphML format to MetaGraphsNext.MGFormat instead of MetaGraphs.MGFormat, since according to the documentation of MetaGraphsNext.jl  it is more performant?

Thanks in adcvance

**Comment by filchristou** [comment]
Hello. Unfortunately it's not possible right now.

**Comment by filchristou** [comment]
And if it will ever be probably that work better to happen in GraphIO.jl directly.

**Comment by finn777-yea** [comment]
OK, thanks anyway
